# Generated by Django 4.1.5 on 2023-01-06 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_status_task_created_task_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 6, 11, 10, 49, 390998, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
